name: Docker image builder

on:
  push:
    branches: 
         - '*'
jobs:
   build:
       runs-on: self-hosted 
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Welcome to Docker world"
               bash init.sh
               docker build -t myfirstimage:v2 .
               echo "Check docker images"
               docker images -a 
   deploy:
       runs-on: self-hosted
       needs: build
       if: github.ref == 'refs/heads/master'
       steps:
          - name: Push docker image to registry
            run: |
                  docker login --username ${{ secrets.REGISTRY_NAME }} --password ${{ secrets.PASSWORD }} 
                  docker tag myfirstimage:v1 alwaysavail/grunt
                  docker push alwaysavail/grunt
        
