name: Docker image builder

on:
  push:
    branches: [ master ]
jobs:
   run_push_request:
       runs-on: self-hosted 
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Welcome to Docker world"
               bash init.sh
               docker build -t myfirstimage:v1 .
               echo "Check docker images"
               docker images -a 
         - name: ssh to deployment machine
           uses: appleboy/scp-action@master 
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              source: "build"
              target: "/opt"
