name: Docker image builder

on:
  push:
    branches: [ master ]
jobs:
   run_push_request:
       runs-on: self-hosted 
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Welcome to Docker world"
               bash init.sh
               docker build -t myfirstimage:v1 .
               echo "Check docker images"
               docker images -a 
         - name: scp init to opt
           run: |
               scp -r init.sh -i ${{ secrets.PASSWORD }} ubuntu@3.84.222.34:/opt
         - name: ssh to deployment machine
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              script: |
                     cat /etc/issue.net
                     ls -lh /opt 
